[phases.setup]
nixPkgs = ["nodejs_20", "vips"]

[phases.install]
cmds = [
  "npm ci --include=optional",
  "npm install --cpu=x64 --os=linux sharp",
  "npm install --cpu=x64 --os=linux lightningcss"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"
