[phases.setup]
nixPkgs = ["nodejs_20", "vips"]

[phases.install]
cmds = [
  "npm ci --omit=optional",
  "rm -rf node_modules/sharp node_modules/lightningcss node_modules/@tailwindcss",
  "npm install --cpu=x64 --os=linux sharp lightningcss",
  "npm install --force @tailwindcss/postcss @tailwindcss/oxide-linux-x64-gnu"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"
